services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: usuario_cbd
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bd_proyecto
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      REDIS_HOST: redis