services:
  almacen-datos:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_cbd
      POSTGRES_PASSWORD: password_cbd
      POSTGRES_DB: bd_proyecto_cbd
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  cache-memoria:
    image: redis:7-alpine
    restart: always
    ports:
      - "6380:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - almacen-datos
      - cache-memoria
    environment:
      DB_HOST: almacen-datos
      REDIS_HOST: cache-memoria
    volumes:
      - .:/app